version: '3.7'

services:
  redis:
    image: redis:alpine
    command: redis-server
    ports:
      - 6379:6379
    networks: 
      - main
    restart: always
  postgres:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=localize
      - POSTGRES_PASSWORD=eecaishi1Eejah0ceNgi
      - POSTGRES_DB=aby
    networks: 
      - main
    restart: always
  django:
    build: ./back
#    command: sh -c "python manage.py migrate --no-input && gunicorn mysite.wsgi -b 0.0.0.0:8000"
    command: sh -c "python manage.py migrate --no-input && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./back/:/usr/src/back/
      - users_files:/usr/src/back/users/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - postgres
    networks:
      - main
    restart: always
  celery:
    build: ./back
    command: celery -A trans_back worker -B -l INFO
    volumes:
      - ./back/:/usr/src/back/
    depends_on:
      - django
      - redis
    networks:
      - main
    restart: always
  react:
    build: ./front
    command: npm start
    volumes:
      - node_modules:/usr/src/front/node_modules
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
    networks: 
      - main
    restart: always
volumes:
  postgres_data:
  users_files:
  node_modules:

networks:
  main: