version: '3.7'

services:
  redis:
    container_name: localize-redis-dev
    image: redis:alpine
    ports:
      - 6379:6379
  postgres:
    container_name: localize-postgres-dev
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=xaxaxue
  django:
    container_name: localize-django-dev
    build: ./back
    image: localize-django-dev
    command: sh -c "python manage.py migrate --no-input && gunicorn localize.wsgi -b 0:8000"
    volumes:
      - ./back:/usr/src/back/
      - users_files:/usr/src/back/users/
    ports:
      - 8000:8000
    depends_on:
      - postgres
  celery:
    container_name: localize-celery-dev
    image: localize-django-dev
    command: celery -A localize worker -B -l INFO
    volumes:
      - users_files:/usr/src/back/users/
    depends_on:
      - django
      - redis
  react:
    container_name: localize-react-dev
    build: ./front
    command: npm start
    volumes:
      - ./front:/usr/src/front/
    environment:
      - REACT_APP_API_URL=http://127.0.0.1:8000/api
    ports:
      - 3000:3000
    tty: true
    stdin_open: true

volumes:
  postgres_data:
  users_files:
