version: '3.7'

services:
  web:
    build: ./back
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./back/:/usr/src/back/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=localize
      - POSTGRES_PASSWORD=eecaishi1Eejah0ceNgi
      - POSTGRES_DB=aby
volumes:
  postgres_data:




