version: '3.7'

services:
  postgres:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=localize
      - POSTGRES_PASSWORD=eecaishi1Eejah0ceNgi
      - POSTGRES_DB=aby
  django:
    build: ./back
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./back/:/usr/src/back/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - postgres
  react:
    build: ./front
    command: ["npm", "start"]
    volumes:
      - ./front:/usr/src/front/
      - node-modules:/usr/src/front/node_modules        
    ports:
      - 3000:3000
volumes:
  postgres_data:
  node-modules:
