// APP: UI ELEMS
export const POPUP_MESSAGE_ADD = "POPUP_MESSAGE_ADD"
export const POPUP_MESSAGE_REMOVE = "POPUP_MESSAGE_REMOVE"
// APP: LOADER
export const INIT_LOADER = "INIT_LOADER"
// APP: LANGUAGES
export const LANGUAGES_REFRESH = "LANGUAGES_REFRESH"
// ACC
export const USER_ACC_VALID = "USER_ACC_VALID"
export const USER_ACC_LOGOUT = "USER_ACC_LOGOUT"
export const USER_ACC_REGISTER = "USER_ACC_REGISTER"
// ROLE: PROJECT CREATOR
export const USER_PROJECT_REFRESH = "USER_PROJECT_REFRESH"
export const USER_PROJECT_ADD = "USER_PROJECT_ADD"
export const USER_PROJECT_REMOVE = "USER_PROJECT_REMOVE"
// ROLE: MANAGE (folders & files)
export const PRJ_FOLDER_REFRESH = "PRJ_FOLDER_REFRESH"
export const PRJ_FOLDER_ADD = "PRJ_FOLDER_ADD"
export const PRJ_FOLDER_REMOVE = "PRJ_FOLDER_REMOVE"

export const EXPLORER_REFRESH = "EXPLORER_REFRESH"
// ROLE: TRANSLATE
export const TRANSLATE_PAGE_REFRESH = "TRANSLATE_PAGE_REFRESH"
export const TRANSLATE_FILE_INFO = "TRANSLATE_FILE_INFO"
export const TRANSLATE_CHANGE = "TRANSLATE_CHANGE"
// ROLE: ADMIN (access)
export const PRJ_PERMISSION_REFRESH = "PRJ_PERMISSION_REFRESH"
export const PRJ_PERMISSION_ADD = "PRJ_PERMISSION_ADD"
export const PRJ_PERMISSION_REMOVE = "PRJ_PERMISSION_REMOVE"
