// APP: UI ELEMS
export const POPUP_MESSAGE_ADD = "POPUP_MESSAGE_ADD"
export const POPUP_MESSAGE_REMOVE = "POPUP_MESSAGE_REMOVE"
// INIT APP
export const INIT_LOADER = "INIT_LOADER"

export const USER_ACC_VALID = "USER_ACC_VALID"
export const USER_ACC_LOGOUT = "USER_ACC_LOGOUT"
export const USER_ACC_REGISTER = "USER_ACC_REGISTER"

export const LANGUAGES_REFRESH = "LANGUAGES_REFRESH"
// ROLE: PROJECT CREATOR
export const USER_PROJECT_REFRESH = "USER_PROJECT_REFRESH"
export const USER_PROJECT_ADD = "USER_PROJECT_ADD"
export const USER_PROJECT_REMOVE = "USER_PROJECT_REMOVE"

export const EXPLORER_LOADING = "EXPLORER_LOADING"
export const EXPLORER_REFRESH = "EXPLORER_REFRESH"
// TODO: FILE/FOLDER CHANGE
// ROLE: TRANSLATE
export const TRANSLATE_PAGE_LOADING = "TRANSLATE_PAGE_LOADING"
export const TRANSLATE_PAGE_REFRESH = "TRANSLATE_PAGE_REFRESH"
export const TRANSLATE_FILE_INFO = "TRANSLATE_FILE_INFO"
export const TRANSLATE_CHANGE = "TRANSLATE_CHANGE"
